server:
  port: 1234

spring:
  application:
    name: cache-redis
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root
    password: coti
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    host: 'localhost'
    virtual-host:
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

rabbit:
  config:
    exchange:
      shopping: "ex_compras"
      sales: "ex_vendas"
    routing:
      shopping: "router_compras"
      sales: "router_vendas"
    queue:
      shopping: "queue_compras"
      sales: "queue_vendas"
      audit: "queue_auditoria"

spring-doc:
  swagger-ui:
    path: /swagger-ui.html