server:
  port: 1234

spring:
  application:
    name: cache-redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/testjpa?serverTimezone=UTC&useSSL=false
    username: root
    password: coti
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show_sql: true
  output:
    ansi:
      enabled: Always

spring-doc:
  swagger-ui:
    path: /swagger-ui.html