server:
  port: 1234

spring:
  application:
    name: cache-redis
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root
    password: coti
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show_sql: true
  output:
    ansi:
      enabled: Always

spring-doc:
  swagger-ui:
    path: /swagger-ui.html